-- Generated by scripts/bundle-sql.mjs — do not edit by hand.
--
-- Every migration, in order, plus the bookkeeping the migration runner
-- keeps. Paste the whole thing into the Supabase SQL editor and run it once.
--
-- Re-running it will fail on the second statement, which is the point: the
-- schema already exists and applying it twice would be wrong.

create table if not exists schema_migrations (
  name        text primary key,
  checksum    text        not null,
  applied_at  timestamptz not null default now()
);

-- ========================================================================
-- 0001_release1_schema.sql
-- ========================================================================

-- Release 1 schema: events, participants, positions, ETAs, feed.
--
-- R1 is guests-only, so there is no accounts or groups table yet — those
-- arrive in R2, and bills in R3 (docs/PLAN.md §14).
--
-- Access model for R1: every read and write goes through a server route
-- handler holding the service-role key, which checks the invite token (and
-- PIN) before touching anything. RLS is therefore enabled with *no* policies,
-- which denies the anon and authenticated roles outright — the API is the
-- only door. R2 replaces this with real per-role policies once accounts exist.

-- ---------------------------------------------------------------- enums ---

create type rsvp_state         as enum ('pending', 'going', 'maybe', 'cant');
create type participant_status as enum ('not_started', 'en_route', 'arrived');
create type travel_mode        as enum ('driving', 'walking', 'transit', 'cycling');
create type tracking_source    as enum ('app_background', 'app_foreground', 'web', 'manual');
create type event_status       as enum ('active', 'cancelled');
create type eta_source         as enum ('routed', 'straight_line');
create type message_kind       as enum ('text', 'joined', 'rsvp', 'checked_in', 'arrived', 'late');

-- --------------------------------------------------------------- events ---

create table events (
  id                uuid primary key default gen_random_uuid(),

  -- PS-4: 128 bits of entropy, base64url, 22 chars. The bearer credential.
  token             text        not null unique,
  check (token ~ '^[A-Za-z0-9_-]{22}$'),

  -- PS-5: optional 4-digit PIN, hashed. Never stored in the clear.
  pin_hash          text,

  title             text        not null default 'Dinner',
  check (char_length(title) between 1 and 80),

  -- FR-7: an event without coordinates cannot produce an ETA, so it is
  -- rejected at creation rather than degrading silently later.
  place_name        text        not null,
  place_address     text        not null,
  place_lat         double precision not null check (place_lat between -90 and 90),
  place_lng         double precision not null check (place_lng between -180 and 180),

  starts_at         timestamptz not null,
  timezone          text        not null,
  status            event_status not null default 'active',

  -- FR-19: three clocks, because location, feed and event records do not
  -- deserve the same lifetime.
  location_purge_at timestamptz not null,
  feed_purge_at     timestamptz not null,
  expires_at        timestamptz not null,

  created_at        timestamptz not null default now()
);

create index events_expiry_idx on events (expires_at);
create index events_location_purge_idx on events (location_purge_at);

-- --------------------------------------------------------- participants ---

create table participants (
  id                uuid primary key default gen_random_uuid(),
  event_id          uuid        not null references events (id) on delete cascade,

  display_name      text        not null,
  check (char_length(display_name) between 1 and 24),

  color             text        not null,
  is_organizer      boolean     not null default false,

  rsvp              rsvp_state          not null default 'pending',
  status            participant_status  not null default 'not_started',
  travel_mode       travel_mode         not null default 'driving',
  tracking_source   tracking_source     not null default 'web',
  sharing           boolean     not null default false,

  -- FR-9: the manual fallback when location is denied or unavailable.
  self_reported_eta timestamptz,
  arrived_at        timestamptz,

  -- PS-6: identity is a hash of a server-issued token, never a client value.
  device_token_hash text        not null,

  created_at        timestamptz not null default now(),

  -- One device is one participant in a given event.
  unique (event_id, device_token_hash)
);

create index participants_event_idx on participants (event_id);

-- FR-14: arrival is sticky, so arrived_at must be set exactly when status is.
alter table participants add constraint participants_arrival_consistent
  check ((status = 'arrived') = (arrived_at is not null));

-- ------------------------------------------------------------ positions ---

-- PS-3: latest position plus a short trail only. The purge job (FR-19) is
-- what keeps this from becoming a location history.
create table positions (
  id             bigserial primary key,
  participant_id uuid   not null references participants (id) on delete cascade,

  lat            double precision not null check (lat between -90 and 90),
  lng            double precision not null check (lng between -180 and 180),
  accuracy_m     real   not null check (accuracy_m >= 0),

  -- Client clock: an offline queue flushes late, and the age of the fix is
  -- what the staleness rules (FR-11) depend on — not when we received it.
  recorded_at    timestamptz not null,
  received_at    timestamptz not null default now()
);

create index positions_participant_recorded_idx
  on positions (participant_id, recorded_at desc);

-- ----------------------------------------------------------------- etas ---

create table etas (
  participant_id uuid primary key references participants (id) on delete cascade,
  eta_at         timestamptz not null,
  distance_m     integer     not null check (distance_m >= 0),
  duration_s     integer     not null check (duration_s >= 0),
  source         eta_source  not null,

  -- The position this was computed from, so FR-11 can decide whether to spend
  -- another routing call.
  computed_from_lat double precision not null,
  computed_from_lng double precision not null,
  computed_at    timestamptz not null default now()
);

-- ------------------------------------------------------------- messages ---

create table messages (
  id             bigserial primary key,
  event_id       uuid        not null references events (id) on delete cascade,

  -- Null for system events: "Marco arrived 7:24" has no author.
  participant_id uuid        references participants (id) on delete set null,

  kind           message_kind not null,
  body           text,
  meta           jsonb,
  created_at     timestamptz not null default now(),

  -- FR-15: text messages carry a body; system events carry structure instead.
  check (
    (kind = 'text' and body is not null and char_length(body) between 1 and 500)
    or (kind <> 'text' and body is null)
  )
  -- Deliberately NOT requiring a system event to have an author: participant_id
  -- is ON DELETE SET NULL, so when someone leaves, their "joined" row survives
  -- with a null author. The feed is a record of what happened, not a list of
  -- who is currently present, and a constraint demanding an author would make
  -- leaving an event fail outright.
);

create index messages_event_created_idx on messages (event_id, created_at desc);

-- ---------------------------------------------------------------- views ---

-- The single most-read query in the product: each participant's newest fix.
create view latest_positions as
select distinct on (participant_id)
  participant_id, lat, lng, accuracy_m, recorded_at, received_at
from positions
order by participant_id, recorded_at desc;

-- ---------------------------------------------------------------- purge ---

-- FR-19: enforced by a scheduled job, not by filtering at read time. Data
-- that is merely hidden has not been deleted.
create or replace function purge_expired() returns table (
  positions_deleted bigint,
  etas_deleted      bigint,
  messages_deleted  bigint,
  events_deleted    bigint
) language plpgsql security definer as $$
declare
  n_positions bigint;
  n_etas      bigint;
  n_messages  bigint;
  n_events    bigint;
begin
  with gone as (
    delete from positions p
    using participants pt, events ev
    where p.participant_id = pt.id
      and pt.event_id = ev.id
      and ev.location_purge_at <= now()
    returning 1
  ) select count(*) into n_positions from gone;

  with gone as (
    delete from etas et
    using participants pt, events ev
    where et.participant_id = pt.id
      and pt.event_id = ev.id
      and ev.location_purge_at <= now()
    returning 1
  ) select count(*) into n_etas from gone;

  with gone as (
    delete from messages ms
    using events ev
    where ms.event_id = ev.id and ev.feed_purge_at <= now()
    returning 1
  ) select count(*) into n_messages from gone;

  -- Cascades take participants, positions, etas and messages with it.
  with gone as (
    delete from events where expires_at <= now() returning 1
  ) select count(*) into n_events from gone;

  return query select n_positions, n_etas, n_messages, n_events;
end;
$$;

-- ------------------------------------------------------------------ rls ---

alter table events       enable row level security;
alter table participants enable row level security;
alter table positions    enable row level security;
alter table etas         enable row level security;
alter table messages     enable row level security;

-- No policies on purpose: anon and authenticated are denied everything, and
-- only the service role (used by our route handlers, never the browser) gets
-- through. R2 adds real policies alongside accounts and roles.

insert into schema_migrations (name, checksum) values ('0001_release1_schema.sql', '74e0afe2e3d1c770')
  on conflict (name) do nothing;

-- ========================================================================
-- 0002_rate_limits.sql
-- ========================================================================

-- PS-7 — rate limits that survive a cold start.
--
-- The obvious implementation is an in-memory counter, which is worthless here:
-- the web app runs as serverless functions, so each invocation may start with
-- an empty map. A four-digit PIN behind a counter that resets on demand is not
-- protected at all. So the counter lives in Postgres and the increment is one
-- atomic statement.
--
-- Fixed window rather than sliding: simpler, one row per key, and the failure
-- mode (a caller getting up to 2x the limit across a window boundary) is
-- irrelevant at these limits.

create table rate_limits (
  key          text        primary key,
  window_start timestamptz not null,
  count        integer     not null check (count >= 0)
);

-- Old rows are garbage after their window closes; the purge job sweeps them.
create index rate_limits_window_idx on rate_limits (window_start);

create or replace function consume_rate_limit(
  p_key    text,
  p_limit  integer,
  p_window interval
) returns table (
  allowed       boolean,
  used          integer,
  retry_after_s integer
) language plpgsql as $$
declare
  v_count        integer;
  v_window_start timestamptz;
begin
  -- One statement, so concurrent callers cannot both read "9 of 10".
  insert into rate_limits as rl (key, window_start, count)
  values (p_key, now(), 1)
  on conflict (key) do update
    set window_start = case
          when rl.window_start + p_window <= now() then now()
          else rl.window_start
        end,
        count = case
          when rl.window_start + p_window <= now() then 1
          else rl.count + 1
        end
  returning rl.count, rl.window_start into v_count, v_window_start;

  return query select
    v_count <= p_limit,
    v_count,
    greatest(0, ceil(extract(epoch from (v_window_start + p_window - now()))))::integer;
end;
$$;

-- Fold rate-limit cleanup into the existing purge so there is one scheduled job.
create or replace function purge_rate_limits(p_older_than interval default interval '1 day')
returns bigint language plpgsql as $$
declare n bigint;
begin
  with gone as (
    delete from rate_limits where window_start < now() - p_older_than returning 1
  ) select count(*) into n from gone;
  return n;
end;
$$;

alter table rate_limits enable row level security;
-- No policies: service role only, like every other R1 table.

insert into schema_migrations (name, checksum) values ('0002_rate_limits.sql', 'ebd374dc8b95f6c2')
  on conflict (name) do nothing;

-- ========================================================================
-- 0003_arrival_dwell.sql
-- ========================================================================

-- FR-14 — arrival needs dwell, not just proximity.
--
-- A single fix inside the geofence is not arrival: GPS drifts indoors and
-- people walk past the door on their way to park. We record when a device
-- first went continuously inside the radius; leaving resets it to null.

alter table participants
  add column arrival_dwell_since timestamptz;

comment on column participants.arrival_dwell_since is
  'When this device last entered the arrival radius continuously. Null when '
  'outside. Arrival fires once this has held for ARRIVAL_DWELL_MS.';

insert into schema_migrations (name, checksum) values ('0003_arrival_dwell.sql', 'edda73b468555b28')
  on conflict (name) do nothing;

-- ========================================================================
-- 0004_message_reads.sql
-- ========================================================================

-- FR-15 — unread counts for the feed tab.
--
-- Deliberately per-participant "last read at", not per-message read receipts.
-- Receipts change how people behave in a thread — they make not replying
-- visible — and this is a feed for coordinating a dinner, not a messenger.

create table message_reads (
  participant_id uuid primary key references participants (id) on delete cascade,
  last_read_at   timestamptz not null default now()
);

-- FR-15 — the author's name is denormalised onto the entry.
--
-- messages.participant_id is ON DELETE SET NULL, so when someone leaves the
-- event their "Marco arrived" line would otherwise become "Someone arrived".
-- The feed is a record of what happened; it should keep reading correctly
-- after the cast changes.
alter table messages add column author_name text;

alter table message_reads enable row level security;
-- No policies: service role only, like every other R1 table.

insert into schema_migrations (name, checksum) values ('0004_message_reads.sql', '550a1fab3b7f07b2')
  on conflict (name) do nothing;

-- ========================================================================
-- 0005_notifications.sql
-- ========================================================================

-- FR-18 — push notifications.

create type notification_kind as enum ('proximity', 'all_here', 'nudge', 'late', 'message');

alter table participants
  -- PS-12: per device, revoked on leave, deleted with the event.
  add column push_token text,
  -- FR-18: per-event mute. Off by default; nobody opts into a dinner app.
  add column muted boolean not null default false;

-- FR-18 — the dedupe ledger.
--
-- "Priya is 5 minutes away" is interesting exactly once. Without a record of
-- what has already gone out, every tick of the notify job would send it again,
-- which is the fastest way to get an app muted for good.
--
-- participant_id is the *subject* of the notification, not the recipient: one
-- proximity alert per person per event, however many people receive it.
create table notifications_sent (
  participant_id uuid              not null references participants (id) on delete cascade,
  kind           notification_kind not null,
  sent_at        timestamptz       not null default now(),
  primary key (participant_id, kind)
);

-- FR-18 — message collapsing is a window, not a once-ever fact, so it lives on
-- the event rather than in the ledger above: a burst of messages inside a
-- minute is one notification, and the next burst is another.
alter table events add column message_notified_at timestamptz;

alter table notifications_sent enable row level security;
-- No policies: service role only, like every other R1 table.

insert into schema_migrations (name, checksum) values ('0005_notifications.sql', 'e164810d585eb5da')
  on conflict (name) do nothing;

-- ========================================================================
-- 0006_cancellation.sql
-- ========================================================================

-- FR-7 — cancelling an event.
--
-- Cancelling is not just a status flag: people may be driving across town with
-- their location being shared. The API stops that (see cancelEvent), and the
-- cancellation itself belongs in the thread like everything else that happened.

alter type message_kind add value if not exists 'cancelled';

-- Who cancelled, and when. Null for the overwhelming majority of events.
alter table events
  add column cancelled_at timestamptz,
  add column cancelled_by uuid references participants (id) on delete set null;

insert into schema_migrations (name, checksum) values ('0006_cancellation.sql', '553cb64edaae4dff')
  on conflict (name) do nothing;
